services:
    _defaults:
        autowire: true

    TomasVotruba\Website\Posts\Year2018\ConsoleDI\:
        resource: ..

    Symfony\Component\Console\Application:
        # why public? so we can get it from container in bin file via "$container->get(Application::class)"
        public: true
