services:
  hugo:
    image: hugomods/hugo:0.161.1
    working_dir: /src
    volumes:
      - ./blog:/src:delegated
    command: ["server", "--bind", "0.0.0.0", "--port", "1313", "--baseURL", "http://localhost:1313/", "--appendPort=false", "--disableFastRender", "--buildDrafts", "--buildFuture"]
    ports:
      - "1313:1313"
