parameters:
    # used by https://www.tomasvotruba.cz/testing-packages/
    testing_package_names:
        - 'behat/behat'
        - 'phpspec/phpspec'
        - 'mockery/mockery'
        - 'nette/tester'
        - 'phpunit/phpunit'
        - 'codeception/codeception'

    # used by https://www.tomasvotruba.cz/package-downloads-by-version/
    versioned_framework_vendor:
        nette: Nette
        symfony: Symfony
        illuminate: Laravel
        cakephp: CakePHP
        zendframework: Zend
        yiisoft: Yii

    # used by https://www.tomasvotruba.cz/php-framework-trends/
    frameworks_vendor_to_name:
        nette: Nette
        symfony: Symfony
        # includes also laravel/framework
        illuminate: Laravel
        cakephp: CakePHP
        # single monorepos
        zendframework: Zend
        yiisoft: Yii
        # microframeworks
        slim: Slim

        # didn't pass the 1000 daily downloads minimal entrance
        # codeigniter: Code Igniter (900)
        # fuel: FuelPHP (618)
        # phalcon: Phalcon (15)
